### ISSUE TITLE
native上的请求如何抓包

### ISSUE THREAD

**Issue by zhoulang27426405** [nohosts/nohost#12]
是否要换一种方式，手机代理指向本地nohost客户端而不是nohost服务器。

**Comment by avwo** [comment]
一般有这几种方式：
1. 设置系统代理
2. vpn 或 proxifier 软件
3. 客户端提供设置代理选项

**Comment by HarryQQ** [comment]
已导入了正式域名证书，手机设置手动代理到nohost的ip和端口。在safari上可以抓https，但native 的https请求就不行。

**Comment by avwo** [comment]
可能跟这个一样: https://github.com/avwo/whistle/issues/429

**Comment by zhoulang27426405** [comment]
了解，谢谢 @avwo
