### ISSUE TITLE
关于前后端访问nohost的问题

### ISSUE THREAD

**Issue by lizy0329** [nohosts/nohost#14]
在官方文档上，前端跟后端的访问方式是不一致的：
后端，只需要安装  SwitchyOmega 请求都转到 nohost 就OK了。
而前端，又要安装 whistle 又要配置远程规则。

这两种方式有不一样的地方么？

经实测，前端安装  SwitchyOmega 请求都转到 nohost 也是OK的

**Comment by avwo** [comment]
后端可以通过代码设置proxy，如果是node可以用https://github.com/avwo/lack，同时带上请求头 x-whistle-nohost-env
