### ISSUE TITLE
nohost小圆点环境切换问题

### ISSUE THREAD

**Issue by xwLyc** [nohosts/nohost#21]
比如现在有两个用户 ，a和b，点击小圆点会出现三个选项，正式环境，a，b。
当用户a选择a环境进行开发时，用户b首次打开的默认就是a环境，然后选择了b环境。
这时候用户a，刷新页面，发现环境变成了b环境，貌似只要有一个用户选择了一个其他用户的都会发生变化。

这个是我配置有问题还是？

能不能做到就是初次打开默认正式环境，然后第一次切换环境存储在本地，这样刷新的时候，直接去取存在本地的环境，就不会被别的用户影响了

**Comment by avwo** [comment]
默认是根据用户ip 来关联环境的，如果部署到外网需要通过 x-whistle-client-is 手动指定环境
