### ISSUE TITLE
docker镜像

### ISSUE THREAD

**Issue by brizer** [nohosts/nohost#22]
有没有考虑提供一个镜像一键部署

**Comment by avwo** [comment]
暂时没时间搞，有空可以帮忙搞一个。

**Comment by WzFFzW** [comment]
提供了https://hub.docker.com/r/nohostjs/nohost

**Comment by avwo** [comment]
nohost 的配置是写到本机硬盘的，用docker部署注意将这些文件持久化。

**Comment by aogg** [comment]
dockerfile呢
