### ISSUE TITLE
入口可以配置localhost吗

### ISSUE THREAD

**Issue by Miiskye** [nohosts/nohost#26]
![image](https://user-images.githubusercontent.com/28433071/100329581-d10b9180-3008-11eb-90cf-545c3ff868ac.png)
![image](https://user-images.githubusercontent.com/28433071/100329752-0b752e80-3009-11eb-9ed6-d673e5adc405.png)
配置了localhost页面没有出现小蓝点，是因为没有代理到吗

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/266

**Comment by Miiskye** [comment]
SwitchyOmega插件加 <-loopback> 可代理到，谢谢

**Comment by ywager** [comment]
@Miiskye @avwo 请问如果使用的nohost客户端，没用SwitchyOmega，入口还可以配置localhost吗，目前配置无效，
抓取不到本地localhost的请求
