### ISSUE TITLE
微信开发者工具用nohost代理后, 怎么选择环境呢? 

### ISSUE THREAD

**Issue by tabris233** [nohosts/nohost#27]
只能在前端代码里面注入圆点嘛? (后台开发, 前端代码改动大点就顶不住了)

**Comment by avwo** [comment]
nohost管理后台首页就是独立的环境选择页面，这个也可以用来选环境。

**Comment by tabris233** [comment]
> nohost管理后台首页就是独立的环境选择页面，这个也可以用来选环境。

了解啦 感谢!
