### ISSUE TITLE
nohost安装whistle.inspect插件失败

### ISSUE THREAD

**Issue by zhoulang27426405** [nohosts/nohost#33]
n2 i whistle.inspect安装插件后，plugins列表显示正常，但是进入查看详情显示Not Found
![image](https://user-images.githubusercontent.com/13732123/103194185-c3a03a80-4919-11eb-8661-1c2d01b95f48.png)

**Comment by avwo** [comment]
Not Found正常，不用管，这个插件没有 UI 界面
