### ISSUE TITLE
nohost客户端上无法像whistle一样切换环境

### ISSUE THREAD

**Issue by zhoulang27426405** [nohosts/nohost#35]
![image](https://user-images.githubusercontent.com/13732123/103329125-5bc32e80-4a96-11eb-89b6-91775b65176d.png)
只能选择default，无法选择test环境

**Comment by avwo** [comment]
这个由用户通过页面自由选择环境，这里选择的目的是什么？

**Comment by zhoulang27426405** [comment]
比如native上的一些环境配置无法在页面上选择，这种时候希望能在这里选择切换

**Comment by avwo** [comment]
访问管理后台首页选择环境即可，这个操作是对整个机器的请求生效

**Comment by zhoulang27426405** [comment]
了解了，谢谢
