### ISSUE TITLE
使用环境切换icon切换当前环境后，出现404请求

### ISSUE THREAD

**Issue by pangmingming** [nohosts/nohost#6]
切换环境或者刷新页面时下面的两个请求偶发性的404，之后页面的切换icon不再加载，请求不能抓包
https://xxx.xxx.xxx/...whistle-path.5b6af7b9884e1165...///whistle.nohost/cgi-bin/select?name=guomingpang&envId=%25E6%259C%25AC%25E5%259C%25B0&time=1577021050430

https://xxx.xxx.xxx/...whistle-path.5b6af7b9884e1165...///whistle.nohost/cgi-bin/list?_=1577022517507

**Comment by avwo** [comment]
1. 本地**不要装** whistle.nohost 插件，那个插件已经废弃
2. 确保远程nohost管理界面下的 nohost 插件启用着
![image](https://user-images.githubusercontent.com/11450939/71398880-dd4ed800-265c-11ea-8047-c48934ee2986.png)

**Comment by pangmingming** [comment]
> 1. 本地**不要装** whistle.nohost 插件，那个插件已经废弃
> 2. 确保远程nohost管理界面下的 nohost 插件启用着
>    ![image](https://user-images.githubusercontent.com/11450939/71398880-dd4ed800-265c-11ea-8047-c48934ee2986.png)

1.本地的我应该删除了，
![image](https://user-images.githubusercontent.com/19421593/71408423-214fd600-2679-11ea-8aa8-fee1eb599719.png)
2.服务器上的nohost也开着的。
![image](https://user-images.githubusercontent.com/19421593/71408470-5825ec00-2679-11ea-91a0-01e536f53588.png)
但还是会出现404的错误请求：
![image](https://user-images.githubusercontent.com/19421593/71408742-3711cb00-267a-11ea-9a1e-4022571f8a85.png)

**Comment by pangmingming** [comment]
本地的nohost卸载之后，又重新install了服务器上的nohost，然后远程nohost就不会在出现这个404的错误请求了
